name: Build, Push, and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_BACKEND_RDS }}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_BACKEND_REDIS }}

      - name: Build and Push backend_rds Docker image
        run: |
          docker build -t backend_rds ./backend_rds
          docker tag backend_rds:latest ${{ secrets.ECR_REPOSITORY_BACKEND_RDS }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_BACKEND_RDS }}:latest

      - name: Build and Push backend_redis Docker image
        run: |
          docker build -t backend_redis ./backend_redis
          docker tag backend_redis:latest ${{ secrets.ECR_REPOSITORY_BACKEND_REDIS }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_BACKEND_REDIS }}:latest

      - name: SSH into EC2 and Deploy Containers
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ec2-user
          CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            docker pull ${{ secrets.ECR_REPOSITORY_BACKEND_RDS }}:latest
            docker pull ${{ secrets.ECR_REPOSITORY_BACKEND_REDIS }}:latest
            docker stop backend_rds || true && docker rm backend_rds || true
            docker stop backend_redis || true && docker rm backend_redis || true
            docker run -d --name backend_rds -p 8000:8000 \
              -e CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS" \
              ${{ secrets.ECR_REPOSITORY_BACKEND_RDS }}:latest
            docker run -d --name backend_redis -p 8001:8001 \
              -e CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS" \
              ${{ secrets.ECR_REPOSITORY_BACKEND_REDIS }}:latest
          EOF
